version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: site-review-postgres
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - site-review-db-data:/var/lib/postgresql/data

volumes:
  site-review-db-data:
